import { LegalPage } from "../legal-content";

const sections=[
{id:"escopo",title:"Introdução e escopo",paragraphs:["Esta política explica como a Destino Andes trata dados pessoais durante a navegação, o atendimento e a prestação de serviços turísticos. O tratamento observa a Lei Geral de Proteção de Dados Pessoais - Lei nº 13.709/2018 (LGPD) - e demais normas aplicáveis.","Ao enviar informações pelos canais do site, o titular declara ciência das práticas descritas nesta política."]},
{id:"dados",title:"Dados pessoais tratados",paragraphs:["Durante a navegação e o atendimento, podem ser tratados dados fornecidos voluntariamente e informações técnicas essenciais. Na contratação, outros dados poderão ser necessários à execução da viagem."],items:["nome, e-mail, telefone ou WhatsApp;","preferências, datas, destinos e perfil da viagem;","idioma e país selecionados, armazenados localmente no navegador;","identificação civil e documentos de viagem;","dados necessários a passagens, hospedagens, seguros, ingressos e transportes;","necessidades de acessibilidade, alimentação ou saúde, somente quando necessárias e autorizadas."]},
{id:"finalidades",title:"Finalidades e bases legais",paragraphs:["Os dados podem ser utilizados para responder contatos, elaborar propostas, confirmar disponibilidade, executar contratos, emitir documentos de viagem, prestar suporte, prevenir fraudes e cumprir obrigações legais.","As bases legais podem incluir procedimentos preliminares, execução de contrato, cumprimento de obrigação legal, legítimo interesse e consentimento, conforme o contexto."]},
{id:"compartilhamento",title:"Compartilhamento com terceiros",paragraphs:["Quando necessário à viagem, somente os dados pertinentes poderão ser compartilhados com operadores receptivos, transportadores, companhias aéreas, hospedagens, seguradoras, plataformas de pagamento e autoridades competentes.","Serviços fora do Brasil podem exigir transferência internacional de dados, observadas salvaguardas compatíveis com a LGPD."]},
{id:"retencao",title:"Retenção e armazenamento",paragraphs:["As informações são conservadas pelo período necessário ao atendimento, à execução da viagem, ao pós-venda e ao cumprimento de obrigações legais ou regulatórias. Encerrada a finalidade, são eliminadas ou anonimizadas, salvo conservação autorizada ou exigida por lei."]},
{id:"direitos",title:"Direitos dos titulares",paragraphs:["Nos termos do artigo 18 da LGPD, o titular pode solicitar, conforme aplicável:"],items:["confirmação da existência de tratamento e acesso;","correção de dados incompletos ou desatualizados;","anonimização, bloqueio ou eliminação de dados desnecessários;","informação sobre compartilhamentos;","portabilidade, quando regulamentada;","revogação do consentimento e eliminação dos dados tratados nessa base."]},
{id:"seguranca",title:"Segurança da informação",paragraphs:["São adotadas medidas técnicas e administrativas proporcionais aos riscos para reduzir acesso não autorizado, perda, alteração, destruição ou tratamento ilícito. Nenhum sistema é absolutamente invulnerável; por isso, controles podem ser revistos continuamente."]},
{id:"cookies",title:"Cookies e preferências locais",paragraphs:["O site pode usar tecnologias essenciais ao funcionamento e ao armazenamento das escolhas de país e idioma. Essas preferências ficam no navegador. Futuras ferramentas de análise ou publicidade deverão ser informadas e submetidas ao consentimento quando exigido.","O usuário pode gerenciar ou apagar dados locais e cookies nas configurações do navegador."]},
{id:"contato",title:"Canal de privacidade",paragraphs:["Para esclarecer dúvidas ou exercer direitos, utilize a página de contato e identifique o assunto como Privacidade e proteção de dados. A identidade do solicitante poderá ser confirmada antes do atendimento para proteção dos próprios dados."]},
{id:"alteracoes",title:"Alterações desta política",paragraphs:["A política pode ser atualizada para refletir mudanças legais, tecnológicas ou operacionais. A versão vigente e sua data serão mantidas nesta página."]},
];
export default function Privacy(){return <LegalPage privacy eyebrow="PRIVACIDADE E PROTEÇÃO DE DADOS" title="Política de Privacidade" subtitle="Como coletamos, utilizamos, armazenamos, compartilhamos e protegemos dados pessoais na Destino Andes." updated="27 de julho de 2026" sections={sections}/>};
