import Link from "next/link";
import { Footer, Header } from "./components";

type Section = { id:string; title:string; paragraphs?:string[]; items?:string[] };
type LegalPageProps = { eyebrow:string; title:string; subtitle:string; updated:string; sections:Section[]; privacy?:boolean };

export function LegalPage({eyebrow,title,subtitle,updated,sections,privacy=false}:LegalPageProps){
  return <><Header/><main><section className={`legal-hero ${privacy?"privacy-hero":""}`}><p className="kicker light">{eyebrow}</p><h1>{title}</h1><p>{subtitle}</p><div className="legal-badges"><span>Informações transparentes</span><span>Atualizado em {updated}</span></div></section><section className="legal-layout section"><aside><strong>Nesta página</strong>{sections.map((section,index)=><a key={section.id} href={`#${section.id}`}><span>{String(index+1).padStart(2,"0")}</span>{section.title}</a>)}</aside><div className="legal-content"><header><p className="kicker">{privacy?"USO RESPONSÁVEL":"ANTES DE CONTINUAR"}</p><h2>{privacy?"Privacidade faz parte do cuidado com a viagem.":"O uso do portal representa a ciência destas condições."}</h2><p>{privacy?<>Consulte também os <Link href="/termos-de-uso">Termos de Uso</Link>.</>:<>Leia também a nossa <Link href="/politica-de-privacidade">Política de Privacidade</Link>.</>}</p><small>Última atualização: {updated}</small></header>{sections.map((section,index)=><article id={section.id} key={section.id}><span>{String(index+1).padStart(2,"0")}</span><div><h2>{section.title}</h2>{section.paragraphs?.map(text=><p key={text}>{text}</p>)}{section.items&&<ul>{section.items.map(item=><li key={item}>{item}</li>)}</ul>}</div></article>)}<div className="legal-contact"><p className="kicker light">FALE COM A DESTINO ANDES</p><h2>{privacy?"Precisa exercer um direito ou tirar uma dúvida?":"Ficou com alguma dúvida sobre estas condições?"}</h2><Link className="btn gold" href="/contato">Ver canais de atendimento</Link></div></div></section></main><Footer/></>;
}
