import Link from "next/link";
import { Footer, Header, TourCard } from "../components";
import { tours } from "../data";

export default function ChileHome() {
  return <><Header/><main>
    <section className="hero">
      <div className="hero-image"><img src="/images/library/cajon-del-maipo-embalse-el-yeso/cajon-del-maipo-embalse-el-yeso-031.webp" alt="Cordilheira dos Andes coberta de neve no Chile"/></div>
      <div className="hero-overlay"/><div className="hero-copy"><p className="kicker light">DESTINO ANDES • CHILE</p><h1>O Chile começa<br/>muito antes da viagem.</h1><p>Começa no cuidado com cada escolha. Criamos passeios autênticos, seguros e organizados para você viver a Cordilheira, os vinhos e o Pacífico no seu ritmo.</p><div className="hero-actions"><Link className="btn gold" href="/chile/passeios">Explorar passeios</Link><Link className="btn glass" href="/contato">Montar meu roteiro</Link></div></div><div className="hero-proof"><span>Especialistas locais</span><span>Atendimento em português, espanhol e inglês</span><span>Curadoria humana</span></div>
    </section>
    <section className="intro"><div><p className="kicker">VIAJE COM PRESENÇA LOCAL</p><h2>Seu tempo no Chile merece mais do que um roteiro pronto.</h2></div><div><p>A Destino Andes combina conhecimento local e atendimento próximo para transformar dias de viagem em experiências que fazem sentido para você.</p><Link className="text-link" href="/chile/como-funciona">Entenda como cuidamos da sua viagem →</Link></div></section>
    <section className="featured section"><div className="section-title"><div><p className="kicker">EXPERIÊNCIAS EM DESTAQUE</p><h2>Escolhas que revelam o Chile</h2></div><Link className="text-link" href="/chile/passeios">Ver todos os passeios →</Link></div><div className="tour-grid">{tours.slice(0,6).map(t=><TourCard key={t.slug} tour={t}/>)}</div></section>
    <section className="split-story"><img src="/images/library/vinicola-alyan/vinicola-alyan-016.webp" alt="Vinhedos chilenos aos pés da Cordilheira"/><div><p className="kicker light">FEITO PARA O SEU JEITO DE VIAJAR</p><h2>Compartilhe o caminho.<br/><em>Ou crie o seu.</em></h2><p>Passeios compartilhados para conhecer mais viajantes, experiências privativas para ter liberdade de ritmo e roteiros personalizados para combinar o melhor dos dois.</p><div className="story-links"><a href="/chile/como-funciona#compartilhados">Passeios compartilhados <span>→</span></a><a href="/chile/como-funciona#privativos">Privativos e personalizados <span>→</span></a></div></div></section>
    <section className="process section"><div className="section-title"><div><p className="kicker">SIMPLES, CLARO E HUMANO</p><h2>Da ideia ao embarque</h2></div></div><div className="steps"><article><b>01</b><h3>Conte seus planos</h3><p>Datas, perfil dos viajantes e experiências que fazem seus olhos brilharem.</p></article><article><b>02</b><h3>Receba nossa curadoria</h3><p>Avaliamos clima, logística e ritmo para recomendar as melhores escolhas.</p></article><article><b>03</b><h3>Confirme com segurança</h3><p>Você recebe valores, condições e todos os detalhes antes de reservar.</p></article><article><b>04</b><h3>Viva o Chile</h3><p>Conte com nosso suporte local antes, durante e depois de cada passeio.</p></article></div></section>
    <section className="cta-banner"><p className="kicker light">SEU PRÓXIMO CAPÍTULO</p><h2>Os Andes estão esperando.<br/>Vamos encontrar o seu caminho?</h2><Link className="btn gold" href="/contato">Falar com um especialista</Link></section>
  </main><Footer/></>;
}
