import { LegalPage } from "../legal-content";

const sections=[
{id:"objeto",title:"Objeto e escopo da plataforma",paragraphs:["O site possui finalidade institucional e comercial: apresenta destinos, passeios e conteúdos editoriais, oferece canais de atendimento e permite solicitar informações, disponibilidade e propostas personalizadas de serviços turísticos.","O alcance destes termos termina na fase de navegação, consulta ou orçamento. A contratação efetiva é formalizada e regida por confirmação, proposta ou instrumento contratual próprio."]},
{id:"contratacao",title:"Condições de cada contratação",paragraphs:["As condições comerciais e operacionais não são fixadas de forma genérica pelo portal. Antes da reserva, o viajante receberá preço definitivo, moeda, meios de pagamento, datas, horários, inclusões, regras de alteração, cancelamento e reembolso aplicáveis ao serviço escolhido."]},
{id:"intermediacao",title:"Natureza da atuação da agência",paragraphs:["A Destino Andes atua na organização e, conforme o serviço, na intermediação entre viajantes e prestadores finais, como operadores receptivos, transportadores, hospedagens, seguradoras e demais fornecedores.","Bagagem, check-in, hospedagem, ingressos e atividades podem seguir condições próprias dos fornecedores, apresentadas na contratação quando aplicáveis."]},
{id:"usuario",title:"Responsabilidades do usuário",paragraphs:["Ao utilizar o portal e seus canais, o usuário compromete-se a:"],items:["fornecer informações verdadeiras, completas e atualizadas;","não enviar dados de terceiros sem autorização;","utilizar a plataforma de boa-fé, sem comprometer sua segurança ou funcionamento;","reconhecer que consultas e cotações não garantem vaga nem congelam tarifas;","confirmar todas as condições antes de efetuar pagamentos."]},
{id:"documentos",title:"Documentação para a viagem",paragraphs:["A regularidade e o porte dos documentos são responsabilidade do passageiro. Isso pode incluir passaporte válido, documento de identidade aceito, vistos, vacinas, autorizações para menores e requisitos migratórios.","As orientações da agência não substituem a conferência das regras oficiais vigentes nem garantem ingresso, embarque ou permanência no destino."]},
{id:"precos",title:"Preços e referências cambiais",paragraphs:["Valores exibidos em moeda diferente daquela cobrada pelo serviço são referenciais. A conversão pode variar até a confirmação da reserva. Promoções, disponibilidade e tarifas podem ser alteradas ou encerradas pelos fornecedores."]},
{id:"propriedade",title:"Propriedade intelectual",paragraphs:["Textos, identidade visual, marcas, logotipos, layouts, fotografias, gráficos e códigos pertencem à Destino Andes ou a titulares que autorizaram seu uso.","É proibida a reprodução, modificação, distribuição ou exploração comercial sem autorização prévia e expressa, ressalvados os usos permitidos em lei."]},
{id:"alteracoes",title:"Alterações destes termos",paragraphs:["Os termos podem ser atualizados para refletir mudanças legislativas, novas funcionalidades ou aperfeiçoamentos operacionais. A versão vigente será identificada pela data de atualização."]},
{id:"legislacao",title:"Legislação e solução de conflitos",paragraphs:["Estes termos são regidos pelas leis da República Federativa do Brasil, inclusive pelo Código de Defesa do Consumidor quando aplicável. Conflitos serão tratados pelos canais oficiais e, se necessário, pelo foro competente definido conforme a legislação."]},
];
export default function Terms(){return <LegalPage eyebrow="INFORMAÇÕES LEGAIS" title="Termos de Uso e Condições Gerais" subtitle="Regras aplicáveis à navegação, aos canais de atendimento e às consultas de serviços turísticos na plataforma Destino Andes." updated="27 de julho de 2026" sections={sections}/>};
